[tool]
[tool.poetry]
authors = ["Your Name <you@example.com>"]
name = "root"
version = "0.0.0"
description="flask template"
[tool.poetry.dependencies]
flask = "==1.0.2"
python = "^3.8"
Flask-WTF = "^0.15.1"
WTForms-Components = "^0.10.5"
email-validator = "^1.1.3"
